function [ numerical_sol ] = ex3_3_simulate( init_position,...
                                        delta_t, num_of_points, ...
                                        lambda,mu ...
                                    )  
    delta_W = randn(num_of_points,1).*sqrt(delta_t);
    numerical_sol=zeros(num_of_points,1);numerical_sol(1,1)=init_position;
    
    for point_index=2:num_of_points
        numerical_sol(point_index,1) = ...
            numerical_sol(point_index-1,1) ...
            + lambda*numerical_sol(point_index-1,1)*delta_t ...
            + mu*delta_W(point_index);
    end
end

